version: '3'
services:
  backend:
    build:
      context: ./TamzaBackend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
  frontend:
    depends_on:
      - backend
    build:
      context: ./TamzaFrontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"